# Generated by Django 5.1.3 on 2024-12-30 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_favoriterecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriterecipe',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='favoriterecipe',
            name='recipe_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='favoriterecipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='favoriterecipe',
            constraint=models.UniqueConstraint(fields=('user', 'recipe_id'), name='unique_user_recipe'),
        ),
    ]
